[package]
name = "proto-defs"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic.workspace = true
tonic-prost.workspace = true
prost.workspace = true
tokio.workspace = true
# prost-derive.workspace = true

[build-dependencies]
tonic-prost-build = "0.14"